#!/bin/sh
set -e

CONF="/etc/bluetooth/main.conf"

replace_or_add() {
   KEY=$1
   VALUE=$2
   if grep -q "^\s*#\?\s*${KEY}" "$CONF"; then
      sed -i "s|^\s*#\?\s*${KEY}.*|${KEY} = ${VALUE}|" "$CONF"
   else
      echo "${KEY} = ${VALUE}" | sudo tee -a "$CONF" >/dev/null
   fi
}

case "$1" in
   configure)
      replace_or_add "Class" "0x240414"
      replace_or_add "DiscoverableTimeout" "0"
      replace_or_add "PairableTimeout" "0"

      systemctl daemon-reload
      systemctl enable simple-bt.service
      systemctl start simple-bt.service
      systemctl enable --now bluealsa
   ;;
esac

exit 0

